
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: hr_management
  username: postgres
  password: root
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hr_management
  pool: 5
  username: postgres
  password: root
  
production:
  <<: *default
  database: db/production.sqlite3
